routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'BlogController@index')->name('home');
Route::get('/isi-post/{slug}', 'BlogController@isi')->name('blog.isi');
Route::get('/list-post', 'BlogController@list_blog')->name('blog.list');
Route::get('/list-category/{category}', 'BlogController@list_category')->name('blog.category');
Route::get('/profile/{users}', 'BlogController@users')->name('blog.users');
Route::get('/cari', 'BlogController@cari')->name('blog.cari');

Route::middleware(['auth'])->group(function () {
  Route::resource('/category', 'CategoryController');
  Route::resource('/tag', 'TagController');
  Route::get('/post/tampil_hapus', 'PostController@tampil_hapus')->name('post.tampil_hapus');
  Route::get('/post/restore/{id}', 'PostController@restore')->name('post.restore');
  Route::delete('/post/kill/{id}', 'PostController@kill')->name('post.kill');
  Route::resource('/post', 'PostController');
  Route::resource('/user', 'UserController');
});

app/Posts.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Posts extends Model
{
  use SoftDeletes;

  protected $fillable = ['judul', 'category_id', 'content', 'gambar', 'slug', 'users_id'];

  public function category()
  {
    return $this->belongsTo('App\Category');
  }

  public function tags()
  {
    return $this->belongsToMany('App\Tags');
  }

  public function users()
  {
    return $this->belongsTo('App\User');
  }

  protected $table = 'posts';
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Posts;
use App\Category;
use App\Tags;
use Auth;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class PostController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    $post = Posts::paginate(10);
    return view('admin.post.index', compact('post'));
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    $category = Category::all();
    $tag = Tags::all();
    return view('admin.post.create', compact('category', 'tag'));
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
    $this->validate($request, [
      'judul' => 'required',
      'category_id' => 'required',
      'content' => 'required',
      'gambar' => 'required'
    ]);

    $gambar = $request->gambar;
    $new_gambar = date('siHdmY') . $gambar->getClientOriginalName();

    $post = Posts::create([
      'judul' => $request->judul,
      'category_id' => $request->category_id,
      'content' => $request->content,
      'gambar' => 'uploads/posts/' . $new_gambar,
      'slug' => Str::slug($request->judul),
      'users_id' => Auth::id()
    ]);

    $post->tags()->attach($request->tags);

    $gambar->move('uploads/posts/', $new_gambar);

    return redirect()->back()->with('success', 'Postingan Anda Berhasil Disimpan');
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function show($id)
  {
    //
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function edit($id)
  {
    $post = Posts::findorfail($id);
    $category = Category::all();
    $tag = Tags::all();
    return view('admin.post.edit', compact('post', 'category', 'tag'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, $id)
  {
    $this->validate($request, [
      'judul' => 'required',
      'category_id' => 'required',
      'content' => 'required'
    ]);

    $post = Posts::findorfail($id);

    if ($request->has('gambar')) {
      $gambar = $request->gambar;
      $new_gambar = date('siHdmY') . $gambar->getClientOriginalName();
      $gambar->move('uploads/posts/', $new_gambar);
      $post_data = [
        'judul' => $request->judul,
        'category_id' => $request->category_id,
        'content' => $request->content,
        'gambar' => 'uploads/posts/' . $new_gambar,
        'slug' => Str::slug($request->judul),
        'users_id' => Auth::id()
      ];
    } else {
      $post_data = [
        'judul' => $request->judul,
        'category_id' => $request->category_id,
        'content' => $request->content,
        'slug' => Str::slug($request->judul),
        'users_id' => Auth::id()
      ];
    }

    $post->tags()->sync($request->tags);
    $post->update($post_data);

    return redirect()->route('post.index')->with('success', 'Postingan Anda Berhasil Diupdate');
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function destroy($id)
  {
    $post = Posts::findorfail($id);
    $post->delete();

    return redirect()->back()->with('success', 'Postingan Anda Berhasil Dihapus (Silahkan cek trashed post)');
  }

  public function tampil_hapus()
  {
    $post = Posts::onlyTrashed()->paginate(10);
    return view('admin.post.hapus', compact('post'));
  }

  public function restore($id)
  {
    $post = Posts::withTrashed()->where('id', $id)->first();
    $post->restore();

    return redirect()->back()->with('success', 'Postingan Anda Berhasil Direstore (Silahkan cek list post)');
  }

  public function kill($id)
  {
    $post = Posts::withTrashed()->where('id', $id)->first();
    $post->forceDelete();

    return redirect()->back()->with('success', 'Postingan Anda Berhasil Dihapus Secara Permanent');
  }
}

resources/views/admin/post/create.blade.php
@extends('template_backend.home')
@section('judul', 'Tambah Post')
@section('content')
  @if (count($errors)>0)
    @foreach ($errors->all() as $error)
      <div class="alert alert-danger" role="alert">
        {{ $error }}
      </div>
    @endforeach
  @endif

  @if (Session::has('success'))
    <div class="alert alert-success" role="alert">
      {{ Session('success') }}
    </div>
  @endif

  <form action="{{ route('post.store') }}" method="post" enctype="multipart/form-data">
    @csrf
    <div class="form-group">
      <label>Judul</label>
      <input type="text" class="form-control" name="judul" autocomplete="off">
    </div>
    <div class="form-group">
      <label>Kategori</label>
      <select class="custom-select" name="category_id">
        <option value="" holder>Pilih Kategori</option>
        @foreach ($category as $d)
          <option value="{{ $d->id }}">{{ $d->name }}</option>
        @endforeach
      </select>
    </div>
    <div class="form-group">
      <label>Pilih Tags</label>
      <select class="form-control select2" multiple="" name="tags[]">
        @foreach ($tag as $d)
        <option value="{{ $d->id }}">{{ $d->name }}</option>
        @endforeach
      </select>
    </div>
    <div class="form-group">
      <label>Content</label>
      <textarea class="summernote" name="content"></textarea>
    </div>
    <div class="form-group">
      <label>Thumbnail</label>
      <input type="file" class="form-control" name="gambar">
    </div>

    <div class="form-group">
      <button class="btn btn-primary btn-block">Simpan Post</button>
    </div>
  </form>
@endsection

resources/views/admin/post/edit.blade.php
@extends('template_backend.home')
@section('judul', 'Edit Post')
@section('content')
  @if (count($errors)>0)
    @foreach ($errors->all() as $error)
      <div class="alert alert-danger" role="alert">
        {{ $error }}
      </div>
    @endforeach
  @endif

  @if (Session::has('success'))
    <div class="alert alert-success" role="alert">
      {{ Session('success') }}
    </div>
  @endif

  <form action="{{ route('post.update', $post->id) }}" method="post" enctype="multipart/form-data">
    @csrf
    @method('patch')
    <div class="form-group">
      <label>Judul</label>
      <input type="text" class="form-control" value="{{ $post->judul }}" name="judul" autocomplete="off">
    </div>
    <div class="form-group">
      <label>Kategori</label>
      <select class="custom-select" name="category_id">
        <option value="" holder>Pilih Kategori</option>
        @foreach ($category as $d)
          <option value="{{ $d->id }}"
            @if ($post->category_id == $d->id)
              selected
            @endif
          >{{ $d->name }}</option>
        @endforeach
      </select>
    </div>
    <div class="form-group">
      <label>Pilih Tags</label>
      <select class="form-control select2" multiple="" name="tags[]">
        @foreach ($tag as $d)
          <option value="{{ $d->id }}"
            @foreach ($post->tags as $value)
              @if ($d->id == $value->id)
                selected
              @endif
            @endforeach
          >{{ $d->name }}</option>
        @endforeach
      </select>
    </div>
    <div class="form-group">
      <label>Content</label>
      <textarea class="summernote" name="content">{{ $post->content }}</textarea>
    </div>
    <div class="form-group">
      <label>Thumbnail</label>
      <input type="file" class="form-control" name="gambar">
    </div>

    <div class="form-group">
      <button class="btn btn-primary btn-block">Update Post</button>
    </div>
  </form>
@endsection

resources/views/admin/post/hapus.blade.php
@extends('template_backend.home')
@section('judul', 'Post Yang Sudah Dihapus')
@section('content')
  @if (Session::has('success'))
    <div class="alert alert-success" role="alert">
      {{ Session('success') }}
    </div>
  @endif

  <table class="table table-striped table-hover table-sm table-bordered">
    <tr>
      <th>No</th>
      <th>Nama Post</th>
      <th>Kategori</th>
      <th>Daftar Tags</th>
      <th>Creator</th>
      <th>Thumbnail</th>
      <th>Action</th>
    </tr>
    @foreach ($post as $result => $d)
      <tr>
        <td>{{ $result + $post->firstitem() }}</td>
        <td>{{ $d->judul }}</td>
        <td>{{ $d->category->name }}</td>
        <td>
          @foreach ($d->tags as $tag)
            <h6><span class="badge badge-info">{{ $tag->name }}</span></h6>
          @endforeach
        </td>
        <td>{{ $d->users->name }}</td>
        <td>
          <img src="{{ asset( $d->gambar ) }}" class="img-fluid" width="100" alt="">
        </td>
        <td>
          <form action="{{ route('post.kill', $d->id) }}" method="post">
            @csrf
            @method('delete')
            <a href="{{ route('post.restore', $d->id) }}" class="btn btn-success btn-sm">Restore</a>
            <button type="submit" class="btn btn-danger btn-sm" name="button">Delete</button>
          </form>
        </td>
      </tr>
    @endforeach
  </table>
  {{ $post->links() }}
@endsection

resources/views/admin/post/index.blade.php
@extends('template_backend.home')
@section('judul', 'Post')
@section('content')
  @if (Session::has('success'))
    <div class="alert alert-success" role="alert">
      {{ Session('success') }}
    </div>
  @endif

  <a href="{{ route('post.create') }}" class="btn btn-primary btn-sm">Tambah Post</a><br><br>
  <table class="table table-striped table-hover table-sm table-bordered">
    <tr>
      <th>No</th>
      <th>Nama Post</th>
      <th>Kategori</th>
      <th>Daftar Tags</th>
      <th>Creator</th>
      <th>Thumbnail</th>
      <th>Action</th>
    </tr>
    @foreach ($post as $result => $d)
      <tr>
        <td>{{ $result + $post->firstitem() }}</td>
        <td>{{ $d->judul }}</td>
        <td>{{ $d->category->name }}</td>
        <td>
          @foreach ($d->tags as $tag)
            <h6><span class="badge badge-info">{{ $tag->name }}</span></h6>
          @endforeach
        </td>
        <td>{{ $d->users->name }}</td>
        <td>
          <img src="{{ asset( $d->gambar ) }}" class="img-fluid" width="100" alt="">
        </td>
        <td>
          <form action="{{ route('post.destroy', $d->id) }}" method="post">
            @csrf
            @method('delete')
            <a href="{{ route('post.edit', $d->id) }}" class="btn btn-success btn-sm">Edit</a>
            <button type="submit" class="btn btn-danger btn-sm" name="button">Delete</button>
          </form>
        </td>
      </tr>
    @endforeach
  </table>
  {{ $post->links() }}
@endsection